### mk-get-miRNA-variants ###
# mkfile script with dependency rules for:
#	1. To separate variants found in PGKB. For more information about PGKB, see https://www.pharmgkb.org/
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.SEPARATE_PGKB:QV: %.PGKB.vcf
	echo "[DEBUG] Done separating variants by PGKB annotated"

## Filter vep is a VEP tool described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html
# -i, input file
# -o, output file
# --vcf_info_field, VEP finds annotations in ANN field
# -filter, VEP finds variants where it matches with "pharmgkb_drug" field.
# --force_overwrite, forces an ouput file
%.PGKB.vcf:Q: %.vcf
	echo "[DEBUG] extracting PGKB variants for $prereq"
	filter_vep \
		-i $prereq \
		-o $target.build \
		--vcf_info_field ANN \
		-filter "pharmgkb_drug" \
		--force_overwrite \
	&& mv $target.build $target
