### mk-get-coding-region-variants ###
# mkfile script with dependency rules for:
#	1. To separate variants found in coding region.
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%.SEPARATE_CODING:QV: %.coding_region.vcf
	echo "[DEBUG] Done separating variants in coding region"

## Filter vep is a VEP tool described here: https://www.ensembl.org/info/docs/tools/vep/script/vep_filter.html
# -i, input file
# -o, output file
# --vcf_info_field, VEP finds annotations in ANN field
# -filter, VEP finds variants where it does not match with "INTRON" and matches with feature type of exons.
# --force_overwrite, forces an ouput file
%.coding_region.vcf:Q: %.vcf
	echo "[DEBUG] extracting coding variants for $prereq"
	filter_vep \
		-i $prereq \
		-o $target.build \
		--vcf_info_field ANN \
		-filter "not INTRON and BIOTYPE is protein_coding and EXON and Protein_position" \
		--force_overwrite \
	&& mv $target.build $target
